### ISSUE TITLE
Output calculation in GNNWR method

### ISSUE THREAD

**Issue by rezashami** [zjuwss/gnnwr#5]
For predicting the y value in the original paper of [GNNWR](https://doi.org/10.1080/13658816.2019.1707834) they multiply three values and sum them.

1. the `spatial weight`
2. `OLS coefficient`
3. and `Independent variables`

Here is the original paper quote: 

> Accordingly, the fitted value ^yi is the result of summing the multiplications of all the nonstationary coefficients and their corresponding independent variables.

But in the [code](https://github.com/zjuwss/gnnwr/blob/0a359e4906061cea838390542561752a13c7b4d6/src/gnnwr/models.py#L320), instead of multiplication of 2 and 3, you use a frozen neural network.

Is it correct?

**Comment by Y-nuclear** [comment]
Thank you for bringing up this issue. In the [code](https://github.com/zjuwss/gnnwr/blob/0a359e4906061cea838390542561752a13c7b4d6/src/gnnwr/models.py#L320), we employ a neural network where the weights are represented by the `OLS coefficient`. This approach aids in aggregating the product of 1, 2, and 3. Since the `coefficient` remains constant throughout the training process, we have designated it as a frozen network.

**Comment by rezashami** [comment]
Thank you for your reply
I mistakenly thought that the variable `coef` inside the loop was the OLS coefficient. However, after doing the manual tracing, I realized that the `coef` variable is the Independent Variables.
